VenketCorePracticeCore/Models/ViewModels/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VenketCorePracticeCore.Models.ViewModels
{
    public class EditRoleViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Role Name is Required")]
        public string RoleName { get; set; }

        public List<string> USers { get; set; }
    }
}

VenketCorePracticeCore/Controllers/AdminRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VenketCorePracticeCore.Models;
using VenketCorePracticeCore.Models.ViewModels;

namespace VenketCorePracticeCore.Controllers
{

    // ye 2sra projec hai Venket ka ye wala theek run ho rha hai 

        //[Authorize(Roles = "Admin")]
    public class AdminRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdminRoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this._roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("CreateRole");
                }

                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }
            return View(model);
        }


        public IActionResult ShowAllRoles()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }


        [HttpGet]

        public async Task
            <IActionResult> EditRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return RedirectToAction("ShowAllRoles");
            }

            var model = new EditRoleViewModel
            {
                RoleName = role.Name,
                Id = role.Id

            };



            return View(model);
        }


        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);
            if(role==null)
            {
                return View();

            }
            else
            {
                role.Name=model.RoleName;
              IdentityResult result =  await  _roleManager.UpdateAsync(role);

                if(result.Succeeded)
                {
                    return RedirectToAction("ShowAllRoles");
                }

                foreach (var errors in result.Errors)
                {
                    ModelState.AddModelError("", errors.Description);
                }


                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUserRole(string RoleId)
        {
            ViewBag.RoleID = RoleId;

            var role = await _roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role Id {RoleId} is not here";

                return View("NotFound");
            }
            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserID = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, RoleId))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }
                model.Add(userRoleViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserRole(List<UserRoleViewModel>model,string RoleId)
        {
            ViewBag.RoleID = RoleId;

            var role = await _roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role Id {RoleId} is not here";

                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserID);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if(!model[i].IsSelected && (await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (i < (model.Count - 1))
                {
                    continue;
                }
                else
                {
                    return RedirectToAction("EditRole", new { id = RoleId });
                }
            }
            return RedirectToAction("EditRole", new { id = RoleId });
        }
    }
}

VenketCorePracticeCore/Views/AdminRole/CreateRole.cshtml
@model RoleViewModel
@{
    ViewBag.Title = "login";

}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="CreateRole" asp-controller="AdminRole" method="post">
                <div asp-validation-summary="All" class="text-danger">

                </div>
                <div class="form-group">
                    <label asp-for="RoleName"></label>
                    <input asp-for="RoleName" class="form-control" />
                    <span asp-validation-for="RoleName"></span>
                </div>

                <input type="submit" class="btn btn-primary" value="Crete Role" />
            </form>
        </div>
    </div>
</div>

VenketCorePracticeCore/Views/AdminRole/EditRole.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit-Role";
}


<h2>Edit Role</h2>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input disabled asp-for="Id" class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button class="btn btn-success" type="submit">Edit Role</button>

            <a asp-action="ShowAllRoles" asp-controller="AdminRole" class="btn btn-warning">Cancel</a>
        </div>
    </div>
</form>

<div class="card">
    <div class="card-header">
        <h3>Add or Remove the Users form this Role</h3>
    </div>
    <div class="card-body">
        <a asp-action="EditUserRole" asp-controller="AdminRole" asp-route-RoleId="@Model.Id">Add User into this Role</a>
    </div>
    <div>

    </div>
</div>

VenketCorePracticeCore/Views/AdminRole/EditUserRole.cshtml
@model List<UserRoleViewModel>


@{ 
    var roleId = ViewBag.RoleID;
}


<form method="post">

    <div class="card">
        <div class="card-header">
            <h3>Add or Remove the Users form this Role</h3>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
            <div class="form-check m-1">


                <input type="hidden" asp-for="@Model[i].UserName" />
                <input type="hidden" asp-for="@Model[i].UserID" />
                <input type="checkbox" asp-for="@Model[i].IsSelected" class="form-check-input" />
                <label class="form-check-label" asp-for="@Model[i].IsSelected">@Model[i].UserName</label>
            </div>
            }
        </div>
        <div class="card-footer">
            <input  type="submit" value="Update" class="btn btn-outline-info" style="width:auto" />
            <a asp-action="EditRole" asp-route-id="@roleId" class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

VenketCorePracticeCore/Views/AdminRole/ShowAllRoles.cshtml
@model IEnumerable<IdentityRole>

@{
    ViewBag.Title = "All-Rols";
}
<h2>All Roles</h2>
<div class="container">
    <div class="row">

        @if (Model.Any())
        {
            foreach (var role in Model)
            {

                <div class="card col-6" style=" margin-top:12px">
                    <div class="card-body">
                        <h5 class="card-title text-success">Role Id: @role.Id</h5>
                        <p class="card-text">Name : @role.</p>
                        <a asp-controller="AdminRole" asp-action="EditRole" asp-route-id="@role.Id" class="card-link btn btn-dark">Edit</a>
                        @*<a asp-controller="AdminRole" asp-action="DeleteRole" asp-route-id="@role.Id" class="card-link btn btn-danger">Delete</a>*@

                        <form method="post" asp-action="DeleteRole" asp-controller="Administration" asp-route-id="@role.Id">

                            <span style="display:none" id="confirmDeletespan_@role.Id">

                                Are you Sure you want to delete ?
                                <button class="btn btn-danger" type="submit">Yes</button>
                                <a href="#" class="btn btn-primary" onclick="DeleteConfirm('@role.Id', false);">No</a>
                            </span>
                        </form>

                        <span id="deletespan_@role.Id">
                            <a href="#" class="btn btn-danger" onclick="DeleteConfirm('@role.Id', true);">Delete</a>
                        </span>
                    </div>
                </div>
            }

        }
        else
        {
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title text-danger">No Roles</h5>
                    <p class="card-text">User the button below to create New Role.</p>
                    <a asp-controller="AdminRole" asp-action="CreateRole" class="card-link">Create</a>
                </div>
            </div>
        }
    </div>
</div>




@section scripts{
    @*<script src="~/lib/jqueryfiles/jquery.js"></script>*@
    <script src="~/scripts/CustomScript.js"></script>

    @*<script type="text/javascript">
            function DeleteConfirm(uniqueID, isDeleted) {
                var deletespan = 'deletespan_' + uniqueID;

                var confirmDeleteSpan = 'confirmDeletespan_' + uniqueID;

                if (isDeleted) {
                    $("#" + deletespan).hide();
                    $("#" + confirmDeleteSpan).show();
                }
                else {
                    $("#" + deletespan).show();
                    $("#" + confirmDeleteSpan).hide();
                }
            }
        </script>*@

}